[config.wallpaper]
command = "feh"
arguments = ["--bg-scale"]

[templates.awesome]
input_path = "~/.config/matugen/templates/awesome.lua"
output_path = "~/.config/awesome/colorscheme.lua"

[templates.ghostty]
input_path = "~/.config/matugen/templates/ghostty"
output_path = "~/.config/ghostty/themes/material"

[templates.gtk3]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-3.0/colors.css'

[templates.gtk4]
input_path = '~/.config/matugen/templates/gtk.css'
output_path = '~/.config/gtk-4.0/colors.css'

[templates.nvim]
input_path = "~/.config/matugen/templates/nvim.lua"
output_path = "~/.config/nvim/palette.lua"

[templates.zellij]
input_path = "~/.config/matugen/templates/zellij.kdl"
output_path = "~/.config/zellij/layouts/default.kdl"
